imports:
  - { resource: "../src/Module/UrlMinimization/Config/services.yaml" }

services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/App/'
